// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuDpgL8x7aPl4YMlsiegb8KokaM-lO15M',
    appId: '1:995642050836:web:5923aabd45ac11ac4c5a01',
    messagingSenderId: '995642050836',
    projectId: 'uitnftcert',
    authDomain: 'uitnftcert.firebaseapp.com',
    storageBucket: 'uitnftcert.appspot.com',
    measurementId: 'G-D1VP3K1G2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6pTHawQh4Lo1J-slMCiqsm7o3M4leGMU',
    appId: '1:995642050836:android:d9fdf3cfb74e60d54c5a01',
    messagingSenderId: '995642050836',
    projectId: 'uitnftcert',
    storageBucket: 'uitnftcert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqai4u5aJR2QT1XpDxUi0jVNGRK9kBTS8',
    appId: '1:995642050836:ios:a641e8f18dd26eab4c5a01',
    messagingSenderId: '995642050836',
    projectId: 'uitnftcert',
    storageBucket: 'uitnftcert.appspot.com',
    iosBundleId: 'com.uit.nftCert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqai4u5aJR2QT1XpDxUi0jVNGRK9kBTS8',
    appId: '1:995642050836:ios:a641e8f18dd26eab4c5a01',
    messagingSenderId: '995642050836',
    projectId: 'uitnftcert',
    storageBucket: 'uitnftcert.appspot.com',
    iosBundleId: 'com.uit.nftCert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuDpgL8x7aPl4YMlsiegb8KokaM-lO15M',
    appId: '1:995642050836:web:fa352c31a85d5bbc4c5a01',
    messagingSenderId: '995642050836',
    projectId: 'uitnftcert',
    authDomain: 'uitnftcert.firebaseapp.com',
    storageBucket: 'uitnftcert.appspot.com',
    measurementId: 'G-FJXSE7ES69',
  );
}
